### ISSUE TITLE
RN method roundToNearestPixel is not used

### ISSUE THREAD

**Issue by marudy** [DaniAkash/react-native-responsive-dimensions#7]
Hi @DaniAkash,

your solution is good, I use a very similar one for my RN projects. The difference from my solution is that I use [`roundToNearestPixel`](https://facebook.github.io/react-native/docs/pixelratio.html#roundtonearestpixel) RN method that rounds a layout size (dp) to the nearest layout size that corresponds to an integer number of pixels. And I was about to create a npm package of my own until I saw yours.

I would be happy to provide a PR, if you are actively maintaining this package :)

Thanks

**Comment by marudy** [comment]
@DaniAkash any updates?

Thanks

**Comment by DaniAkash** [comment]
Thanks @marudy PRs are welcome. I'll be publishing a new release soon
