### ISSUE TITLE
responsiveFontSize() not working on samsung glaxy note 8

### ISSUE THREAD

**Issue by amitrai988** [DaniAkash/react-native-responsive-dimensions#8]
for ios its working fine below is screenshot
![simulator screen shot - iphone 6 - 2018-04-25 at 14 54 46](https://user-images.githubusercontent.com/34301373/39237321-d092c642-4898-11e8-9f1b-bc5059c6146e.png)
 
but for androd its not working only on this device 
![screenshot_20180423-134218](https://user-images.githubusercontent.com/34301373/39237344-e30f6f78-4898-11e8-9f50-f02df827ab83.jpg)

Device specification :- 

Resolution | 1440 x 2960 pixels, 18.5:9 ratio (~521 ppi density)
Size | 6.3 inches, 101.1 cm2 (~83.2% screen-to-body ratio)

**Comment by DaniAkash** [comment]
responsiveFontSize uses device height and width to calculate the fontSize. I think the font is bigger cuz the screen height is bigger in Samsung. Try using responsiveWidth for the font size...

**Comment by DaniAkash** [comment]
Version 2.0.0 has been released which will calculate responsiveFontSize using width alone and hence will look uniform across all devices despite the aspect ratio...
